version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password #change
      MYSQL_DATABASE: wordpress #change
      MYSQL_USER: wordpress #change
      MYSQL_PASSWORD: wordpress #change
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "100:80" #change
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress #change
      WORDPRESS_DB_PASSWORD: wordpress #change
      WORDPRESS_DB_NAME: wordpress #change
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example #change
    ports:
      - "101:80" #change
    restart: always
volumes:
    db_data:
